### ISSUE TITLE
[Suggestion] Make content download asynchronnous

### ISSUE THREAD

**Issue by Kuba314** [IamEld3st/youtube_dash_dl#2]
Waiting for linear GET requests takes a lot of time.

**Comment by IamEld3st** [comment]
Will work on threading when I rewrite dash parsing and change how intermediary files are saved because currently I'm just taking segment downloads and appending them to a single ts file... And remux that to a single mp4 file.

**Comment by IamEld3st** [comment]
Download was made asynchronous in rewrite version (#13) and in old version (#6)... closing.
