### ISSUE TITLE
yt_ddl not in path

### ISSUE THREAD

**Issue by Kuba314** [IamEld3st/youtube_dash_dl#8]
After installing with `pip3`, `yt_ddl` is not in path.

**Comment by IamEld3st** [comment]
For it to be in path your python3 script folder needs to be in path aswell as be careful as if python has no permissions for installing scripts in global install it installs it in user scripts location!

**Comment by IamEld3st** [comment]
@Kuba314 do you have any other information about this issue or can I close it?

**Comment by Kuba314** [comment]
I think the problem happened on my side since this isn't the only package that didn't install properly on my machine.
